name = "backend"
compatibility_date = "2024-09-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmE2NjBkODctODgxZi00ZWQ2LWExNDktMTZjMTRmNDU1YzhiIiwidGVuYW50X2lkIjoiMWQ4NDMxOTk0MDIzYmRjMzhiMzA3ZTc4NzAwMjI4ZTgxMTcyMmExNjBkZGNmNmM3YmRmZmZlYzMwOWNmY2QxOCIsImludGVybmFsX3NlY3JldCI6ImQ1MTA0M2I3LTJkYTctNDIwNy05MmM5LTllMDRmNGZjZWI2NSJ9.qxryRTXk-91DC_GrTYsT_7o_fbgT6Sr-hzOsHENNiiY"
JWT_SECRET="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"